#!/usr/bin/perl
use strict;
use warnings;
use Switch;
use Time::Piece;

my $date = localtime->strftime('%Y-%m-%d');
my $input = '';
clear_screen();
print"********************\n";
print"Make Project Script\n";
print"********************\n";
print"please provide a project name\n";
my $name = <STDIN>;
print"please provide project details/readme\n";
my $deets = <STDIN>;
print"Please also list tags\n";
my $tags = <STDIN>;

#storage Dir, ideally in projects folder
my $dirStorage = "/home/jammers/Project_archive/$name";
my $prjStorage = "/home/jammers/Zettel/GoblinKnows/FOREST/04-dataBase/projects/$name.md";
my $tskStorage = "/home/jammers/Zettel/GoblinKnows/TOOLS/projectFile_taskList/$name.md";

my $input = '';

while ($input ne '6')
{
    clear_screen();
    print "********************\n".
     "Make Project Script\n".
     "********************\n".
     "1. Create a storage directory\n".
     "2. create a project file in Obsidian\n". 
     "3. create a taskList file in Obsidian\n". 
     "4. choose a licence\n". 
     "5. games\n".
     "6. exit\n";

    print "Enter your choice: ";
    $input = <STDIN>;
    chomp($input);
    switch ($input)
    {
        case '1'
        {
            clear_screen();
            print "\nSuccess, Directory created!\n";
            mkdir $dirStorage;

        }
        case '2'
        {
            $input = '';
            while ($input ne '4')
            {
                clear_screen();
                print "1. edit > option 1\n".
                      "2. edit > option 1\n".
                      "3. edit > option 3\n".
                      "4. return to main menu\n";

                print "Enter your choice: ";
                $input = <STDIN>;
                chomp($input);
            }
            $input = '';
        }
        case '3'
        {
            $input = '';
            while ($input ne '4')
            {
                clear_screen();
                print "1. edit > option 1\n".
                      "2. edit > option 1\n".
                      "3. edit > option 3\n".
                      "4. return to main menu\n";

                print "Enter your choice: ";
                $input = <STDIN>;
                chomp($input);
            }
            $input = '';
        }        
        case '4'
        {
            $input = '';
            while ($input ne '4')
            {
                clear_screen();
                print "1. edit > option 1\n".
                      "2. edit > option 1\n".
                      "3. edit > option 3\n".
                      "4. return to main menu\n";

                print "Enter your choice: ";
                $input = <STDIN>;
                chomp($input);
            }
            $input = '';
        }
    }
}
exit(0);
sub clear_screen {
    system("clear");
}

sub prompt {
  my ($query) = @_; # take a prompt string as argument
  local $| = 1; # activate autoflush to immediately show the prompt
  print $query;
  chomp(my $answer = <STDIN>);
  return $answer;
}
sub prompt_yn {
  my ($query) = @_;
  my $answer = prompt("$query (Y/N): ");
  return lc($answer) eq 'y';
}