#!/usr/bin/perl
use warnings;
use Time::Piece;

my $date = localtime->strftime('%Y-%m-%d');
print "please offer a name: ";
my $name = <STDIN>;
chomp($name);
print "please offer some tags seperated by a space: ";
my $tags = <STDIN>;
chomp($tags);
print "please offer priority; ";
my $priority = <STDIN>;
chomp($priority);
my $projfile = "/home/jammers/Zettel/GoblinKnows/FOREST/04-dataBase/projects/$name.md";
open(my $fh, '>', $projfile) or die "could not open file '$projfile' $!";
print $fh "---\n".
"alias:\n".
"cssclass:\n".
"lastReviewed:\n".
"tags: $tags\n".
"isProject: true\n".
"note:\n".
"priority: $priority\n".
"projCompleted:\n".
"projectMain: $name\n".
"projectType:\n".
"status: planning\n".
"date: $date\n".
"---\n\n".
"# $name\n\n\n\n\n".
"```dataview\n".
"task\n".
"from \"TOOLS\"\n".
"where !completed & projectMain = \"$name\" & type = \"taskList\"\n".
"```\n\n\n".
"[[$name-taskList]]\n".
"[link to locally stored files](file:///home/jammers/Project_archive/$name)";

close $fh;
print "done project page\n";
my $taskfile = "/home/jammers/Zettel/GoblinKnows/TOOLS/projectFile_taskLists/$name-taskList.md";
open(my $tf, '>', $taskfile) or die "could not open file '$taskfile' $!";
print $tf "---\n".
"cssstyle:\n".
"isProject: true\n".
"projectMain: $name\n".
"type: taskList\n".
"date: $date\n".
"---\n\n\n".
"# $name-taskList\n".
"[[$name|Link to main project]]";
close $tf;
print "done taskList page\n";